# Generated by Django 4.2.9 on 2024-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiuser',
            name='chat_id',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
