# Generated by Django 4.2.9 on 2024-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notiuser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
