# Generated by Django 5.0.3 on 2024-03-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(default='', max_length=200)),
                ('data_type', models.CharField(default='', max_length=200)),
                ('data_version', models.CharField(default='', max_length=200)),
                ('date_reserved', models.CharField(default='', max_length=200)),
                ('date_publish', models.CharField(default='', max_length=200)),
                ('date_update', models.CharField(default='', max_length=200)),
                ('assigner_Org_Id', models.CharField(default='', max_length=200)),
                ('provider_Metadata', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CvssV20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='', max_length=200)),
                ('vector_string', models.CharField(default='', max_length=300)),
                ('base_score', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CvssV30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='', max_length=200)),
                ('vector_string', models.CharField(default='', max_length=300)),
                ('base_score', models.FloatField(default='')),
                ('base_severity', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CvssV31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='', max_length=200)),
                ('vector_string', models.CharField(default='', max_length=300)),
                ('base_score', models.FloatField(default='')),
                ('base_severity', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='', max_length=3000)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=9000)),
                ('con_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='description_cves', to='firstapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='metric_cve', to='firstapp.cve')),
                ('cvssv20', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='metric_cvss_v20', to='firstapp.cvssv20')),
                ('cvssv30', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='metric_cvss_v30', to='firstapp.cvssv30')),
                ('cvssv31', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='metric_cvss_v31', to='firstapp.cvssv31')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=3000)),
                ('con_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='references_cves', to='firstapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=9000)),
                ('con_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='solutions_cves', to='firstapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Affected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_id', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='affected_cves', to='firstapp.cve')),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor', to='firstapp.products')),
                ('vendor', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_product', to='firstapp.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Products_Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='firstapp.products')),
                ('version', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='version_product', to='firstapp.versions')),
            ],
        ),
    ]
