# Generated by Django 5.0.3 on 2024-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='assigner_Org_Id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cve_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='data_version',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_publish',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_reserved',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_update',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cve',
            name='provider_Metadata',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvssv20',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvssv30',
            name='base_severity',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvssv30',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvssv31',
            name='base_severity',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cvssv31',
            name='version',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='versions',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
