# Generated by Django 5.0.3 on 2024-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_cve_assigner_org_id_alter_cve_cve_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvssv31',
            name='vector_string',
            field=models.CharField(default='', max_length=400),
        ),
    ]
