# Generated by Django 5.0.3 on 2024-03-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_cvssv31_vector_string'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affected',
            old_name='con_id',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='descriptions',
            old_name='con_id',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='con_id',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='references',
            old_name='con_id',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='solutions',
            old_name='con_id',
            new_name='con',
        ),
    ]
