# Generated by Django 5.0.3 on 2024-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_alter_descriptions_value_alter_solutions_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='assigner_Org_Id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_publish',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_reserved',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_update',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='provider_Metadata',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv20',
            name='base_score',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cvssv20',
            name='vector_string',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv20',
            name='version',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv30',
            name='base_score',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cvssv30',
            name='base_severity',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv30',
            name='vector_string',
            field=models.CharField(default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv30',
            name='version',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv31',
            name='base_score',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cvssv31',
            name='base_severity',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv31',
            name='vector_string',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cvssv31',
            name='version',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='url',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='name',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='versions',
            name='status',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='versions',
            name='version',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
    ]
