# Generated by Django 5.0.3 on 2024-03-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_cve_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cve',
            name='data_version',
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_reserved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
