# Generated by Django 5.0.3 on 2024-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_cve_data_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='date_publish',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_reserved',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='date_update',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
