# Generated by Django 5.0.3 on 2024-04-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_follow_affected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_affected',
            name='affected',
        ),
        migrations.AddField(
            model_name='follow_affected',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follow_product', to='firstapp.products'),
        ),
    ]
