# Generated by Django 5.0.3 on 2024-04-04 17:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_remove_follow_affected_affected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow_Affected',
            new_name='Follow_Product',
        ),
    ]
