# Generated by Django 5.0.3 on 2024-04-25 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_rename_follow_affected_follow_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='assignerShortName',
            field=models.CharField(default='', max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='title',
            field=models.CharField(default='', max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='attackComplexity',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='attackVector',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='availabilityImpact',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='confidentialityImpact',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='integrityImpact',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='privilegesRequired',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='scope',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvssv31',
            name='userInteraction',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products_versions',
            name='con',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productversion_cves', to='firstapp.cve'),
        ),
        migrations.AddField(
            model_name='versions',
            name='type',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Exploits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=9000, null=True)),
                ('con', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exploits_cves', to='firstapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Follow_CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follow_cve', to='firstapp.cve')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_cve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=9000, null=True)),
                ('con', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='platforms_cves', to='firstapp.cve')),
            ],
        ),
        migrations.AddField(
            model_name='affected',
            name='platform',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='affected_platform', to='firstapp.platforms'),
        ),
        migrations.CreateModel(
            name='ProblemTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cweId', models.CharField(default='', max_length=255, null=True)),
                ('description', models.CharField(default='', max_length=9000, null=True)),
                ('con', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='problemtypes_cves', to='firstapp.cve')),
            ],
        ),
        migrations.CreateModel(
            name='Workaround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=9000, null=True)),
                ('con', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='workaround_cves', to='firstapp.cve')),
            ],
        ),
    ]
