# Generated by Django 5.0.3 on 2024-04-26 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_rename_follow_cve_followcve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowCVE',
            new_name='Follow_CVE',
        ),
        migrations.RenameModel(
            old_name='FollowProduct',
            new_name='Follow_Product',
        ),
        migrations.RenameModel(
            old_name='ProductsVersions',
            new_name='Products_Versions',
        ),
        migrations.RemoveField(
            model_name='affected',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='problemtypes',
            name='lang',
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
    ]
